### PR TITLE
Fix pytest

### PR DESCRIPTION
**Pull request by panesofglass**
My test run failed due to a missing `js2py` dependency, so I added that and froze the dependencies.

### CODE REVIEW

**Comment by davidkpiano** [comment]
Thanks, wondering if adding just `Js2Py` is sufficient, or are all the other deps necessary to be in the requirements file?

**Comment by panesofglass** [comment]
@davidkpiano probably just Js2Py is sufficient. I typically use the `pip freeze > requirements.txt`, but I would be happy to revert and add just the one dependency if you prefer. I'll update the PR.

**Comment by davidkpiano** [comment]
> @davidkpiano probably just Js2Py is sufficient. I typically use the `pip freeze > requirements.txt`, but I would be happy to revert and add just the one dependency if you prefer. I'll update the PR.

Sure, can you revert it to just one dep? Thank you!

**Comment by panesofglass** [comment]
@davidkpiano done

**Pull request merged**
